site_name: Documentación Técnica - Taller ACA
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

nav:
  - Inicio: index.md
  - Guía de Instalación: instalacion.md
  - Características: caracteristicas.md